server:
  port: 8080
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:postgresql://114.115.160.150:5500/td_test
          username: postgres
          password: tdpassword
          drive-class-name: org.postgresql.Drive
        slave_1:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:postgresql://114.115.160.150:5500/td_test_slave01
          username: postgres
          password: tdpassword
          drive-class-name: org.postgresql.Drive